vidas=5
i=5

print('the prince continued with his mission in the castle')
input()
print('he turned down and founded on the floor a candle and a matchstick')
input()
print('CLICK ENTER TO GRAB THE CANDLE AND MATCHSTICK')
input()

print('the prince founded a door and opened it')
input()
print('he entered in a large and dark room...')
input()
print('the prince just crossed the door and...')
input()
print('CRACK!!')
input()
print('the door closed right behind him')
input()
print('prince: wooh! that was scary')
input()
print('he decided to turn on the candle to have some light')
print('as he walked into the room he feels that someone was behind him')
input()
print('but that room seemed to have nothing interesting')
input()
print('the prince crossed the room and found a door')
input()
print('he opened it and...')
input()
print('there was a lot of stairs in front of him')
input()
print('prince: this castle is enormous')
input()
print('ELF APPEARS')
input()
print('elf:hi, your next challenge is right in front of you')
input()
print('prince: those stairs??')
input()
print('elf: you are right')
input()
print('prince: okay so this challenge is about climbing stairs, easy')
input()
print('elf: oh no my friend, dont underestimate these stairs')
input()
print('elf:in this challenge there are a lot of stairs but there are also fireballs and you should cross without a single burn')
input()
print('elf:i will tell you three times a pattern of numbers according to the stairs that you will need to climb between the fireballs and you should memorize it')
input()

print('CLICK ENTER TO START THE CHALLENGE')
input()

print('elf:the number of steps are:')
input()
for n in [1,2,3]:
  print("121322")

  
input()

while True:
  answer=input("enter the correct pattern of numbers")
  if answer=='121322':
    print('YOU DID IT!')
    break
  elif (answer!="121322"):
    print('thats not the pattern, you lose a life')
    i=i-1
    print("you have" ,i, "tries")
    break

print('prince:oof!, another challenge done')
input()
print('the prince turned around and saw a big hall with a light at the end that seemed to be the way out')
input()
print('the prince ran all the way through the hall')
input()
print('at the end of the hall there was the exit')
print('the prince arrived to a beautiful yard with a lake, an arch and an sculpture of the beautiful princess')
input()
print('prince: WOW🤩, this place is beautiful')
input()
print('the prince knelt in front of the sculpture of the princess')
input()
print('suddenly a knight with a enormous horse appeared')
input()
print('prince:who are you??')
input()
print('choose the name of the knight')
name=input 
print('im sir',name,'and im here to take you with the princess')
input()
print('prince mind: hmm, this knight looks suspicious')
input()
print('prince: okay, so what are we waiting for?')
input()
print(name,'get on my horse')
input()
print(name,'we need to ride some kilometers to get to the bridge')
input()
print('the prince got on the horse and ride with the night untill they arrived to a large bridge')
input()
print(name,'well we arrived, we need to cross the bridge and there is the tower of the princess')
input()
print('prince: that bridge seems to be unstable and dangerous')
input()
print(name,'you go first my friend')
input()
print('prince:well, i cant wait to see the love of my life')
input()
print('the prince started walking through the bridge...')
input()
print('even if this trembled')
input()
print('but the knight had other plans...')
input()
print('the knight cutted the rope of the bridge😨')
input()
print('why?')
input()
print('because he was in love with the princess but the rules where that only a prince could be with the princess')
input()
print('but our brave prince hanged from the bridge... ')
input()
print('and climbed to the other side')